<?php
$title = 'Delete book';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
  '<?= $this->escapeHtml($book->title); ?>' by
  '<?= $this->escapeHtml($book->author); ?>'?
</p>
<?php
$url = $this->url('book', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?= $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?= (int)$book->id; ?>" />
  <input type="submit" name="del" class="btn btn-danger" value="Yes" />
  <input type="submit" name="del" class="btn btn-default" value="No" />
</div>
</form>
